### ISSUE TITLE
Future version comment still says the report was resolved as awaiting response

### ISSUE THREAD

**Issue by Greymagic27** [mojira/helper-messages#161]
## The bug
[Arisa PR #725](https://github.com/mojira/arisa-kt/pull/725) changed the future version module by making it resolve reports as invalid rather than awaiting response, however the comment still contains the message 'This issue is being temporarily closed as Awaiting Response. Once the requested information has been delivered, the report will be reopened automatically.'
## Example Ticket
https://bugs.mojang.com/browse/MC-232220
## Expected behavior
This message should be changed to reflect the new resolution

**Comment by Marcono1234** [comment]
Maybe we should also reconsider if https://github.com/mojira/arisa-kt/pull/725 is the correct approach, or if it should be limited.
For example regarding reports for the wrong project we were told by the developers to prefer moving them to the correct project instead of resolving them as Invalid to avoid losing valid reports.
I think the same applies here as well; if reports about 1.18 world generation are getting out of hand, then we should try to only resolve these reports as Invalid.

Therefore, it would make sense in my opinion to keep the existing message, and add a new one for the report being resolved as Invalid, or we could even use the message added by #160.
A sophisticated solution could be to have a config entry for Arisa's `FutureVersion` module, mapping from version (or version ID?) to custom Invalid message key, e.g.:
```yml
resolveAsInvalid:
  - 20215: experimental-snapshot
```

@chandler05, what do you think?

**Comment by Greymagic27** [comment]
I like that idea. If it goes ahead I'll scrap my PR and see if I can carefully work out how to make a new helper message

**Comment by violine1101** [comment]
Personally I don't think future version set to AR is a good idea. I feel like straight invalid would be way more helpful in most cases, if there is no other version that's been selected.

I only see these reasons for why someone selects an unreleased version:
* They are in the wrong project. In this case the bug report would be invalid anyway, and the message notifies them that they've chosen the wrong project.
* They report something for an unreleased version. In this case the bug report would be invalid anyway.
* They don't know the version they're playing on. In this case I don't think AR would be particularily helpful.

**Comment by Marcono1234** [comment]
To me it rather looks like many reports are for the correct project (see also [query](https://bugs.mojang.com/issues/?jql=resolution%20%3D%20Invalid%20and%20comment%20~%20"unreleased%20version%20We%20have%20removed%20it%20and%20added%20the%20latest%20released%20version"%20order%20by%20createdDate)).

And we were told not to resolve reports for wrong projects as Invalid (unless they are missing information), so I don't think we should use wrong project as potential reason why automatically resolving as Invalid is fine.

Regarding unreleased versions, and in particular the experimental snapshots https://github.com/mojira/arisa-kt/pull/734 might have helped to avoid some confusion, though maybe it is too late now given that the latest snapshot contains the content of the experimental snapshots.

**Comment by osfanbuff63** [comment]
Is this really still necessary since we merged [Arisa PR 740]? (https://github.com/mojira/arisa-kt/pull/740)
